AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - '**/Rakefile'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'
  NewCops: enable
  TargetRailsVersion: 7.1.3.4
  TargetRubyVersion: 3.3.0

FactoryBot/ConsistentParenthesesStyle:
  Enabled: true
FactoryBot/FactoryNameStyle:
  Enabled: true
FactoryBot/SyntaxMethods:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true
Gemspec/RequireMFA:
  Enabled: true

Layout/AccessModifierIndentation:
  EnforcedStyle: indent
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/EmptyLineAfterMagicComment:
  Enabled: true
Layout/EmptyLinesAroundBlockBody:
  Enabled: true
Layout/EmptyLinesAroundClassBody:
  Enabled: true
Layout/EmptyLinesAroundModuleBody:
  Enabled: true
Layout/LineContinuationLeadingSpace:
  Enabled: true
Layout/LineContinuationSpacing:
  Enabled: true
Layout/LineEndStringConcatenationIndentation:
  Enabled: true
Layout/LineLength:
  Exclude:
    - 'features/**/*'
    - 'spec/**/*'
    - 'Gemfile'
  Max: 120
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true
Lint/AmbiguousOperatorPrecedence:
  Enabled: true
Lint/AmbiguousRange:
  Enabled: true
Lint/AssignmentInCondition:
  AllowSafeAssignment: true
Lint/ConstantOverwrittenInRescue:
  Enabled: true
Lint/DeprecatedConstants:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateMagicComment:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/EmptyClass:
  Enabled: true
Lint/EmptyInPattern:
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
Lint/NonAtomicFileOperation:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/NumberedParameterAssignment:
  Enabled: true
Lint/OrAssignmentToConstant:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Lint/RefinementImportMethods:
  Enabled: true
Lint/RequireRangeParentheses:
  Enabled: true
Lint/RequireRelativeSelfPath:
  Enabled: true
Lint/SymbolConversion:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Lint/UnexpectedBlockArity:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Lint/UselessRuby2Keywords:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'
    - 'config/initializers/markdown_handler.rb'

Naming/BlockForwarding:
  Enabled: true
Naming/VariableNumber:
  EnforcedStyle: 'snake_case'

Performance/AncestorsInclude:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/BlockGivenWithExplicitBlock:
  Enabled: true
Performance/CollectionLiteralInLoop:
  Enabled: true
Performance/ConcurrentMonotonicTime:
  Enabled: true
Performance/ConstantRegexp:
  Enabled: true
Performance/MapCompact:
  Enabled: true
Performance/MethodObjectAsBlock:
  Enabled: true
Performance/RedundantEqualityComparisonBlock:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantSplitRegexpArgument:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringIdentifierArgument:
  Enabled: true
Performance/StringInclude:
  Enabled: true
Performance/Sum:
  Enabled: true

Rails/ActionControllerFlashBeforeRender:
  Enabled: true
Rails/ActionControllerTestCase:
  Enabled: true
Rails/ActionOrder:
  Enabled: true
Rails/ActiveRecordAliases:
  Enabled: true
Rails/ActiveRecordCallbacksOrder:
  Enabled: true
Rails/ActiveSupportOnLoad:
  Enabled: true
Rails/AddColumnIndex:
  Enabled: true
Rails/AfterCommitOverride:
  Enabled: true
Rails/ApplicationMailer:
  Enabled: true
Rails/AttributeDefaultBlockValue:
  Enabled: true
Rails/CompactBlank:
  Enabled: true
Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: true
Rails/DotSeparatedKeys:
  Enabled: true
Rails/DuplicateAssociation:
  Enabled: true
Rails/DuplicateScope:
  Enabled: true
Rails/DurationArithmetic:
  Enabled: true
Rails/EagerEvaluationLogMessage:
  Enabled: true
Rails/EnvironmentVariableAccess:
  Enabled: true
Rails/ExpandedDateRange:
  Enabled: true
Rails/FindById:
  Enabled: true
Rails/FreezeTime:
  Enabled: true
Rails/HttpPositionalArguments:
  Enabled: true
Rails/I18nLazyLookup:
  Enabled: true
Rails/I18nLocaleAssignment:
  Enabled: true
Rails/I18nLocaleTexts:
  Enabled: true
Rails/IgnoredColumnsAssignment:
  Enabled: true
Rails/Inquiry:
  Enabled: true
Rails/MailerName:
  Enabled: true
Rails/MatchRoute:
  Enabled: true
Rails/MigrationClassName:
  Enabled: true
Rails/NegateInclude:
  Enabled: true
Rails/Pluck:
  Enabled: true
Rails/PluckInWhere:
  Enabled: true
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: true
Rails/RedundantTravelBack:
  Enabled: true
Rails/RenderInline:
  Enabled: true
Rails/RenderPlainText:
  Enabled: true
Rails/RootJoinChain:
  Enabled: true
Rails/RootPathnameMethods:
  Enabled: true
Rails/RootPublicPath:
  Enabled: true
Rails/ShortI18n:
  Enabled: true
Rails/SquishedSQLHeredocs:
  Enabled: true
Rails/TimeZoneAssignment:
  Enabled: true
Rails/ToFormattedS:
  Enabled: true
Rails/ToSWithArgument:
  Enabled: true
Rails/TopLevelHashWithIndifferentAccess:
  Enabled: true
Rails/TransactionExitStatement:
  Enabled: true
Rails/UnusedIgnoredColumns:
  Enabled: true
Rails/WhereEquals:
  Enabled: true
Rails/WhereExists:
  Enabled: true
Rails/WhereMissing:
  Enabled: true
Rails/WhereNot:
  Enabled: true
Rails/WhereNotWithMultipleConditions:
  Enabled: true

RSpec/BeEq:
  Enabled: true
RSpec/BeNil:
  Enabled: true
RSpec/Capybara/FeatureMethods:
  Enabled: true
RSpec/ChangeByZero:
  Enabled: true
RSpec/ClassCheck:
  Enabled: true
RSpec/ContextWording:
  Enabled: true
RSpec/DescribedClass:
  Exclude:
    - 'spec/controllers/concerns/quiz_form_handler_spec.rb'
RSpec/DescribeClass:
  Exclude:
    - spec/support/**/*
    - spec/views/**/*
RSpec/DuplicatedMetadata:
  Enabled: true
RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'
RSpec/ExpectActual:
  Exclude:
    - 'spec/routing/**/*'
RSpec/ExcessiveDocstringSpacing:
  Enabled: true
RSpec/IdenticalEqualityAssertion:
  Enabled: true
RSpec/MultipleExpectations:
  Enabled: true
RSpec/MultipleMemoizedHelpers:
  Max: 6
  Enabled: true
RSpec/NestedGroups:
  Max: 10
RSpec/NoExpectationExample:
  Enabled: true
RSpec/PendingWithoutReason:
  Enabled: true
RSpec/RepeatedExampleGroupBody:
  Enabled: true
RSpec/SortMetadata:
  Enabled: true
RSpec/SpecFilePathFormat:
  Exclude:
    - spec/routing/**/*
RSpec/SubjectDeclaration:
  Enabled: true
RSpec/VerifiedDoubleReference:
  Enabled: true

RSpecRails/AvoidSetupHook:
  Enabled: true
RSpecRails/HaveHttpStatus:
  Enabled: true
RSpecRails/InferredSpecType:
  Enabled: true

Security/CompoundHash:
  Enabled: true
Security/IoMethods:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true
Style/ArrayIntersect:
  Enabled: true
Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - 'spec/**/*'
Style/ClassAndModuleChildren:
  EnforcedStyle: nested
Style/CollectionCompact:
  Enabled: true
Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    each_with_object: 'inject'
    inject: 'inject'
    reduce: 'inject'
    detect: 'find'
    find_all: 'select'
Style/ConcatArrayLiterals:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: true
Style/EachWithObject:
  Enabled: true
Style/EndlessMethod:
  Enabled: true
Style/EnvHome:
  Enabled: true
Style/FetchEnvVar:
  Enabled: true
Style/FileRead:
  Enabled: true
Style/FileWrite:
  Enabled: true
Style/FormatString:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: true
Style/HashConversion:
  Enabled: true
Style/HashExcept:
  Enabled: true
Style/HashSyntax:
  Enabled: true
Style/IfUnlessModifier:
  Enabled: true
Style/IfWithBooleanLiteralBranches:
  Enabled: true
Style/InPatternThen:
  Enabled: true
Style/MagicCommentFormat:
  Enabled: true
Style/MapCompactWithConditionalBlock:
  Enabled: true
Style/MapToHash:
  Enabled: true
Style/MultilineInPatternThen:
  Enabled: true
Style/NestedFileDirname:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/NumberedParameters:
  Enabled: true
Style/NumberedParametersLimit:
  Enabled: true
Style/NumericLiterals:
  Enabled: true
Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
Style/ObjectThen:
  Enabled: true
Style/OpenStructUse:
  Enabled: true
Style/OperatorMethodCall:
  Enabled: true
Style/OptionalBooleanParameter:
  Enabled: true
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'
    '%W': '[]'
    '%i': '[]'
Style/QuotedSymbols:
  Enabled: true
Style/RedundantArgument:
  Enabled: true
Style/RedundantConstantBase:
  Enabled: true
Style/RedundantDoubleSplatHashBraces:
  Enabled: true
Style/RedundantEach:
  Enabled: true
Style/RedundantInitialize:
  Enabled: true
Style/RedundantSelfAssignmentBranch:
  Enabled: true
Style/RedundantStringEscape:
  Enabled: true
Style/SelectByRegexp:
  Enabled: true
Style/SignalException:
  Enabled: true
Style/StringChars:
  Enabled: true
Style/StringLiterals:
  Enabled: true
Style/SwapValues:
  Enabled: true
Style/SymbolArray:
  Enabled: true
Style/SpecialGlobalVars:
  Enabled: true
Style/TrivialAccessors:
  AllowPredicates: true
Style/WordArray:
  Exclude:
    - 'spec/**/*'

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails
